[package]
name = "arpgn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.38.0"
ash-window = "0.13.0"
bytemuck = "1.15.0"
env_logger = "0.11.3"
log = { version = "0.4.21", features = ["kv"] }
structopt = "0.3.26"
winit = "0.29.15"
# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
debug = 2
split-debuginfo = "packed"
